services:
  fsn:
    build: .
    container_name: fsn-platform
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=d6hE5zBIyU+Du04A63V3YS+Vp8SUd+1LjqAPGJooURQZpN21Xnn0TYHKuXkJm/s5
      - NEXTAUTH_URL=https://fsn.212.227.88.180.nip.io
      - NEXTAUTH_URL_INTERNAL=http://fsn:3000
      - UPLOAD_DIR=/app/uploads
    volumes:
      - fsn-uploads:/app/uploads
      - fsn-db:/app/prisma
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  fsn-uploads:
  fsn-db:
